=== Testing the Persistence Layer
Now we will write some tests to verify that our persistence layer is working as expected.

==== Writing a Test
The basic structure of a repository layer test is:

. Create a new object.
. Save the object to the database using the repository.
. Read the object from the database using the repository.
. Assert that the object from the database has the correct attributes.

Use dependency injection (via the `@Autowired` annotation) to get an instance of your repository. Also add the `@Test` annotation to each test method.

You also want to clear the database after each run so that you don't waste storage space and so that you avoid violating any unique constraints. Define a method `clearDatabase()` with the annotation `@AfterEach` that clears all relevant tables.

Create a class to test the persistence of `Person` objects. It should look something like this:

``` 
package ca.mcgill.ecse321.eventregistration.dao;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import ca.mcgill.ecse321.eventregistration.model.Person;

@SpringBootTest
public class PersonRepositoryTests {
	@Autowired
	private PersonRepository personRepository;
	
	@AfterEach
	public void clearDatabase() {
		personRepository.deleteAll();
	}
	
	@Test
	public void testPersistAndLoadPerson() {
		// Create object
		String name = "Anakin Skywalker";
		Person anakin = new Person();
		anakin.setName(name);
		
		// Save object
		anakin = personRepository.save(anakin);
		int id = anakin.getId();
		
		// Read object from database
		anakin = personRepository.findPersonById(id);
		
		// Assert that object has correct attributes
		assertNotNull(anakin);
		assertEquals(name, anakin.getName());
	}
}
```

Create a class to test the persistence of `Registration` objects. It should look something like this:
``` 
package ca.mcgill.ecse321.eventregistration.dao;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.sql.Date;
import java.sql.Time;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import ca.mcgill.ecse321.eventregistration.model.Event;
import ca.mcgill.ecse321.eventregistration.model.Person;
import ca.mcgill.ecse321.eventregistration.model.Registration;

@SpringBootTest
public class RegistrationRepositoryTests {
	@Autowired
	private PersonRepository personRepository;
	@Autowired
	private EventRepository eventRepository;
	@Autowired
	private RegistrationRepository registrationRepository;
	
	@AfterEach
	public void clearDatabase() {
		// Delete the registrations first to avoid violating not-null constraint
		registrationRepository.deleteAll();
		
		personRepository.deleteAll();
		eventRepository.deleteAll();
	}
	
	@Test
	public void testPersistAndLoadRegistration() {
		String eventName = "Order 66";
		Date date = Date.valueOf("2022-09-06");
		Time startTime = Time.valueOf("16:00:00");
		Time endTime = Time.valueOf("17:00:00");
		Event event = new Event();
		event.setName(eventName);
		event.setEventDate(date);
		event.setStartTime(startTime);
		event.setEndTime(endTime);
		// You need to manually save this before saving the registration: Hibernate doesn't seem to do it for you
		eventRepository.save(event);
		
		String participantName = "Anakin Skywalker";
		Person participant = new Person();
		participant.setName(participantName);
		participant = personRepository.save(participant);
		int participantId = participant.getId();
		
		Registration registration = new Registration();
		registration.setEvent(event);
		registration.setParticipant(participant);
		
		registration = registrationRepository.save(registration);
		int registrationId = registration.getId();
		
		registration = null;
		event = null;
		participant = null;
		
		registration = registrationRepository.findRegistrationById(registrationId);
		
		assertNotNull(registration);
		assertEquals(registrationId, registration.getId());
		
		assertNotNull(registration.getEvent());
		assertEquals(eventName, registration.getEvent().getName());
		
		assertNotNull(registration.getParticipant());
		assertEquals(participantId, registration.getParticipant().getId());
	}
}

``` 

Creating a class to test the persistence of `Event` objects is left as an exercise. It is similar to the test class for `Person` objects.

